// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tair.Data.Context;

namespace Tair.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TairDbContext))]
    [Migration("20240731133445_InserindoImagemNosVoos")]
    partial class InserindoImagemNosVoos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tair.Domain.Entities.Voos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoriaDeVoo")
                        .HasColumnType("int");

                    b.Property<string>("ImagemGrande")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImagemMedia")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImagemPequena")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PrecoCartao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoPix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadePax")
                        .HasColumnType("int");

                    b.Property<int>("TempoDeVooMinutos")
                        .HasColumnType("int");

                    b.Property<int>("TipoDeVoo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Voos");
                });
#pragma warning restore 612, 618
        }
    }
}
